### ISSUE TITLE
Different compression algorithms + levels

### ISSUE THREAD

**Issue by marapper** [siddharthkp/bundlesize#140]
**Feature**

***What is the current behavior?***

`gzip-size` uses `zlib`.

***What is the expected behavior?***

https://github.com/erwinmombay/brotli-size

https://github.com/marapper/zopfli-size

```
{
  "path": "...",
  "maxSize": "3KB",
  "algorithm": "zlib"
}
```

OR

```
      {
      "path": "./dist/dll.js",
      "real": {
        "maxSize": "1.3MB",
        "level": 6
      },
      "zlib": {
        "maxSize": "260KB",
        "level": 9
      },
      "zopfli": {
        "maxSize": "250KB",
        "level": 6
      },
      "brotli": {
        "maxSize": "220KB",
        "level": 6
      }
    }
```

Root `maxSize` can be used as default for bc.

zlib/zopfli/brotli can be optional: it will be required on demand and dependencies will be in `peerDependencies`

***If this is a feature request, what is motivation or use case for changing the behavior?***

In real cases we use zopfli/brotli (for modern browsers) as compression algorithms with nginx.

---- 

Merged from https://github.com/siddharthkp/bundlesize/issues/138 by @siddharthkp

This [PR](https://github.com/sindresorhus/gzip-size/pull/8) will add zlib options to function arguments.

So we can add option `level`

```
  "bundlesize": [
    {
        ...
        "maxSize": "30KB",
        "level": 6
```

In many real cases we use lower gz compression level for assets (js, css, html) to fasten compression/decompression. So with this options we could check real size restrictions.

**Comment by siddharthkp** [comment]
Hey @marapper, that's an interesting idea

However, I don't see value in implementing multiple compression algorithms.

I see value in using the same compression as your application uses on production for more accuracy, but I don't think the use case is big enough.

Another reason to shy away from this is that this problem can be solved in user-land, as you are in charge of building your bundle, you can pass already compressed files to bundlesize (bundlesize always zlibs, we can look into disabling compression on demand to avoid incorrect results due to double compression if that can become a problem)

What do you think?

**Comment by FezVrasta** [comment]
It would make sense for the new brotli compression, all the major browsers support it now.

**Comment by palashmon** [comment]
Closing this issue for now because it has not had recent activity. Thank you for your contributions.
