### ISSUE TITLE
Feature: Check against total file size

### ISSUE THREAD

**Issue by manniL** [siddharthkp/bundlesize#205]
**Do you want to request a *feature* or report a *bug*?**

A feature

**What is the current behavior?**

Bundlesize currently checks if each file is below the threshold.

**What is the expected behavior?**

With a flag set (e.g. `checkAgainstTotal`), bundlesize should sum up the size of all (selected) files and check it against a threshold.

**If this is a feature request, what is motivation or use case for changing the behavior?**

In times of code splitting, it can happen that you have 100 files <3kb, but in the end, this still means that the app is large.

**Comment by siddharthkp** [comment]
Thanks for taking the time!

bundlesize tries to shy away from total size because the performance of a page depends a lot on the way the individual bundles load (prefetch/lazy-load/on-demand, etc.)

We've had discussions around `total` in the past and it doesn't make sense to drive confidence from a metric that is biased/nuanced.

One strategy that has worked for teams using bundlesize is to measure initial bundles and chunks with different thresholds:

```json
"bundlesize": [
  { "path": "./dist/feature-*.js", "maxSize": "30 kB"},
  { "path": "./dist/chunk-*.js", "maxSize": "5 kB" }
]
```

**Comment by manniL** [comment]
@siddharthkp Thanks for that fast answer! I understand now why the measurement of individual files makes more sense than measure the total file size. :relaxed:

**Comment by vanslly** [comment]
Total size makes sense for setting a library size budget for an npm package you publish. Sure the consuming application could cherry-pick & tree-shake the code paths unused, but as a library author it still makes sense to measure & set budgets for the code published in an npm package.

To achieve this I'm resorting to rollup to generate a bundle for me, and then I run bundlesize over this bundle.

**Comment by siddharthkp** [comment]
@vanslly that's a great implementation detail
