### ISSUE TITLE
CLI config

### ISSUE THREAD

**Issue by leggsimon** [siddharthkp/bundlesize#33]
What are your thoughts on adding config via a CLI as an alternative to using `package.json`. We'd love to start using this on our apps but would rather not have to update each apps' `package.json`?

I'd be happy to attempt a PR but want to know your thoughts?

**Comment by siddharthkp** [comment]
I'm in for a different format of config.

CLI params might not be the best idea because there's a bunch of information you can give (multiple files, etc.)

Having a `bundlesize.config.json` could be one approach. `.bundle.yml` if you want a nicer name 😄 
Not sure if that solves your problem though, Adding a block to `package.json` vs copy pasting new file is pretty much the same.

However, it does open up the option of using a compiled version of bundlesize with other languages in the future.

**Comment by leggsimon** [comment]
So thinking of some other tools that have a few ways of configuring it, there seems to be a sort of option of 
 a. `package.json` properties (as bundlesize currently uses)
 b. `.config.yml` or `.config.json`
 c. CLI args
For simple things you could use CLI but then when you want more config you can move to a or b to make it less bloated.
I think CLI is good for simple config like
```sh
$ bundlesize --file /dist/*.js --threshold 3kb
```

**Comment by siddharthkp** [comment]
Okay, I'm sold

**Comment by leggsimon** [comment]
Mind if I have a go at this then?

**Comment by siddharthkp** [comment]
Go for it!

**Comment by siddharthkp** [comment]
@leggsimon I think we should skip option b for now (`config.yml`) and only implement CLI params

**Comment by siddharthkp** [comment]
Implemented in https://github.com/siddharthkp/bundlesize/pull/60
