### ISSUE TITLE
Is it safe to publicize BUNDLESIZE_GITHUB_TOKEN ?

### ISSUE THREAD

**Issue by maestromac** [siddharthkp/bundlesize#356]
**Do you want to request a *feature* or report a *bug*?**
bug I guess?

**What is the current behavior?**
We're trying to integrate bundlesize to our Travis CI and receiving we're `WARN  github token not found`. My assumption is that our fork workflow is limiting how secret/token can be accessed. The most immediate action that comes to mind is to provide the token in `.travis.yml` unencrypted but README does not explicitly state if the token must be kept private.

Is it safe to publicize `BUNDLESIZE_GITHUB_TOKEN`?

**What is the expected behavior?**
Perhaps an updated instruction similar to [how CodeClimate does theirs](https://docs.codeclimate.com/docs/finding-your-test-coverage-token#section-should-i-keep-my-test-reporter-id-secret)

**Please mention other relevant information.**
- Travis CI
- Ruby on Rails + Preact App

**Comment by Haroenv** [comment]
No, the GitHub token is private

**Comment by fgerschau** [comment]
Just encrypt it with
```
travis encrypt BUNDLESIZE_GITHUB_TOKEN="your-key" --add env.global
```
or add it as an environment variable in the settings of your travis repo

**Comment by maestromac** [comment]
@fgerschau Thanks for the suggestion but that wouldn't work because PR from forked repository won't have access to it [ref](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml)
> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

**Comment by siddharthkp** [comment]
@maestromac You are right. CI tools don't expose the token in forks to protect your tokens. The solution to this is not to make your token public either :)

I have an alternate solution in mind and will test it in the beta branch soon 👍

**Comment by rhymes** [comment]
@siddharthkp any updates on the alternate solution? Thank you!

**Comment by siddharthkp** [comment]
Hey! I'm working on a new version (1.0.0) of bundlesize that fixes all of these problems. For source repo - it uses github apps + checks

Don't have a solution for forks yet - but something I want to play around with more. 

1. If there is a way to get source repo from the fork in CI environments then it would be very easy. 
2. Otherwise, might want to add an additional row in bundlesize config which identifies the repo
3. I'm not sure if it can be read from .git/config or package.json to avoid step 2

Ideas welcome

----

If you'd like you can try it out: https://github.com/siddharthkp/bundlesize2

Migration path: 
1. Use the npm package `bundlesize2` instead of `bundlesize`
2. If you'd like status reported back to github, use the flag `--enable-github-checks` + authorize bundlesize2 app. [More in the docs](https://github.com/siddharthkp/bundlesize2#build-status-and-checks-for-github)
3. If anything breaks, let me know :)

Note: This is only until the new version is ready and then it will be merged back in this project as a major release

**Comment by maestromac** [comment]
@siddharthkp yes Travis provides `TRAVIS_REPO_SLUG` which should return the source repo ([source](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables)). 

I think the new version sound like the exact solution we need. I'm going to give bundlesize2 a try soon and let you know.

**Comment by maestromac** [comment]
@siddharthkp initial use seems to be working without issue 👍 . Will let you know if we hit anything

**Comment by siddharthkp** [comment]
Closing the issue here. But will explore fork use case in the other repo
