### ISSUE TITLE
bundlesize-store.now.sh not working for private repos?

### ISSUE THREAD

**Issue by fgerschau** [siddharthkp/bundlesize#358]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When running `npx bundlesize` in TravisCI the request to `bundlesize-store.now.sh` fails with the following error message:
`Error: Request failed with status code 500`

**If the current behavior is a bug, please provide the steps to reproduce.**

```
  config: {
    url: 'https://bundlesize-store.now.sh/values?repo=fitogram/widget&token=[secure]',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.19.2'
    },
    ...
}
```

**What is the expected behavior?**
I'm not sure if this should work for private repositories.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version **v12.16.3**
- npm version **6.14.4**
- Operating system **Ubuntu 16.04.6 LTS**
- bundlesize version **^0.18.0**
- CI you are using **TravisCI**

**Comment by siddharthkp** [comment]
Hey! It definitely should work with private repos as well. 

But, it might be broken. I'm working on a new version (1.0.0) of bundlesize that fixes all of these problems. 

To not break any of the applications that use bundlesize with npx or with `@latest`, I'm building in a separate repo + app (until it's ready) 

If you'd like you can try it out: https://github.com/siddharthkp/bundlesize2

Migration path: 
1. Use the npm package `bundlesize2` instead of `bundlesize`
2. If you'd like status reported back to github, use the flag `--enable-github-checks` + authorize bundlesize2 app. [More in the docs](https://github.com/siddharthkp/bundlesize2#build-status-and-checks-for-github)
3. If anything breaks, let me know :)

Note: This is only until the new version is ready and then it will be merged back in this project as a major release

**Comment by fgerschau** [comment]
Cool, thanks a lot! I'll try this for now
