### ISSUE TITLE
Optimise the details page url format to fit more data

### ISSUE THREAD

**Issue by siddharthkp** [siddharthkp/bundlesize#80]
The details page url takes all the data in query params.

The url seems to be cut off at 835 characters which leaves about 797 characters for data. The current implementation is pretty naive. It stringifies the results object and passes it in the url. This works great for a few files (< 5?), but breaks after that.

A more compact format will help in supporting a bigger number of files.

code: [reporter.js](https://github.com/siddharthkp/bundlesize/blob/master/src/reporter.js#L52-L56) and [store/index.js](https://github.com/siddharthkp/bundlesize/blob/master/store/index.js#L51-L77)

**Comment by karanjthakkar** [comment]
I checked the url link and it seems to be strip off at 1024 despite the github commit status API return the target_url correctly. Now seeing that the value is so exact, I think its a max length trimming on their end.

I cant think of two ideas for now:
1. Store the generated data object somewhere (firebase preferrably since you already have it setup), and just pass the id/hash in the details url. Use the hash/id to fetch the data on the `/build` route and display the details.
  - Pros: Can capture and show more data probably?
  - Cons: Storage costs for firebase? Old data can be nuked in monthly/fortnightly cron job

2. Create a new build context per file
  - Pros: No extra complex implementation
  - Cons: None that I can think of.

What do you think?

**Comment by vs1682** [comment]
@siddharthkp  @karanjthakkar  I guess this issue is resolved and should be closed, right?

**Comment by siddharthkp** [comment]
Oh yeah totally!

:tada:
